[package]
name = "noisefence-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
toml = "0.9"
libfuzzer-sys = "0.4"
noisefence = { path = ".." }
tokio = { version = "1", features = ["rt", "io-util", "time"] }

[[bin]]
name = "message"
path = "fuzz_targets/message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "smtp"
path = "fuzz_targets/smtp.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]

[[bin]]
name = "protection"
path = "fuzz_targets/protection.rs"
test = false
doc = false
bench = false
