DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
Checks 12
Foreground true
TestDatabases true
ConnectTimeout 20
ReceiveTimeout 60
LogSyslog true
LogTime true
NotifyClamd /etc/clamav/clamd.conf
