import { type Assessment, type RecipientDecision, receiptAssessment, receiptDecision, missingCheckLabels } from './assessment.ts';

type DecisionInput = {
  recipient_decision?: RecipientDecision | null;
  assessment?: Assessment;
  delivery_classification?: string | null;
  category: string;
  complete: boolean;
  score: number;
  tagged: boolean;
  pub_tagged: boolean;
  decision?: { source: string; outcome: string; score: number | null };
};

export type ScoreInput = {
  recipient_decision?: RecipientDecision | null;
  assessment?: Assessment;
  score: number | null;
  complete: boolean;
  model?: string;
  decision?: {
    source: string;
    outcome: string;
    score: number | null;
    model?: string;
  } | null;
  arbitration?: { resolution: string } | null;
  reasons?: { id: string }[];
  evidence?: { lexical_state?: string } | null;
  antivirus?: { status: string };
};

// A missing decision score is an abstention, not a missing content score.
// This presentation must never feed classification, thresholds or delivery.
export function scorePresentation(mail: ScoreInput) {
  const valid = (value: unknown): value is number =>
    typeof value === 'number' &&
    Number.isFinite(value) &&
    value >= 0 &&
    value <= 100;
  const recorded = receiptAssessment(mail);
  const report = recorded?.version === 1 ? recorded : undefined;
  const decision = report?.decision ?? mail.decision;
  const useDecision = decision?.source !== 'antivirus' && valid(decision?.score);
  const value = report
    ? (valid(report.score.value) ? report.score.value : null)
    : useDecision
    ? decision!.score
    : valid(mail.score)
      ? mail.score
      : null;
  const model = report?.score.model ?? (useDecision ? decision?.model : mail.model) ?? '';
  const complete = report?.complete ?? mail.complete;
  const resolution = report?.score_resolution;
  if (resolution) {
    const classification = resolution.decision.outcome === 'unwanted' ? 'Spam' : 'Not spam';
    return {
      value, model,
      kind: value === null ? 'unavailable' : complete ? 'content' : 'partial',
      label: value === null ? 'Score unavailable' : complete ? 'Risk index' : 'Partial risk index',
      detail: (value === null
        ? 'No usable score was recorded. The automatic policy accepts the message without inventing a risk value.'
        : `Engine classification: ${classification} by configured threshold: content index ${value.toFixed(2)} / 100, threshold ${resolution.threshold.toFixed(2)}. This index is not a spam probability.`)
        + (report?.classification_source === 'recipient_policy' ? ' Recipient rules determine the final category and delivery action shown separately.' : '')
        + (complete ? '' : ' Analysis remains partial; missing checks are listed separately.')
        + (resolution.projected ? ' This is a current-policy view of historical evidence; the original decision and delivery are preserved.' : ' Detector disagreements remain recorded; no manual review is required.'),
    };
  }
  if (value === null)
    return {
      value,
      model,
      kind: 'unavailable',
      label: 'Score unavailable',
      detail:
        'No usable score was recorded. Missing analysis cannot be represented by zero.',
    };

  if (!complete) {
    const controls = missingCheckLabels;
    const missing = [
      ...new Set(
        (report?.incomplete_reasons ?? (mail.reasons ?? []).map(r => r.id))
          .map((id) => (Object.hasOwn(controls, id) ? controls[id] : null))
          .filter(Boolean),
      ),
    ];
    if (!report && ['unavailable', 'unscannable'].includes(mail.antivirus?.status ?? ''))
      missing.push('antivirus');
    const limited = mail.evidence?.lexical_state === 'limited';
    return {
      value,
      model,
      kind: 'partial',
      label: 'Partial risk index',
      detail: `Risk index based on available results${limited ? ', with limited content extraction' : ''}. ${missing.length ? `Incomplete checks: ${missing.join(', ')}. ` : ''}Missing results could change this index. Analysis remains partial.${decision?.source === 'antivirus' ? ' The antivirus detection takes priority.' : mail.reasons?.some(r => r.id === 'observed_threat_partial') ? ' Corroborated phishing evidence still supports the unwanted verdict; delivery follows the recorded action policy.' : ''}`,
    };
  }
  if (report ? report.score.kind === 'internal' : mail.model === 'dsn')
    return {
      value,
      model,
      kind: 'internal',
      label: 'Internal value',
      detail:
        'Delivery notification generated by NoiseFence. This stored value is not an analysis of incoming mail.',
    };
  if (decision?.source === 'antivirus')
    return {
      value,
      model,
      kind: 'advisory',
      label: 'Advisory risk index',
      detail:
        'Recorded content index. Malware detected by the antivirus takes priority over this score.',
    };
  if (decision?.outcome === 'undetermined') {
    const explanation =
      mail.reasons?.some(r => r.id === 'context_requires_review')
        ? 'Authenticated reporting or receipt context conflicts with the content model.'
        : mail.reasons?.some(r => r.id === 'llm_inconsistent')
          ? 'The LLM category and risk estimate are inconsistent.'
          : mail.arbitration?.resolution === 'disagreement'
            ? 'Detector opinions disagree.'
            : mail.arbitration?.resolution === 'ambiguous'
              ? 'The second opinion is uncertain.'
              : decision.source === 'fusion'
                ? 'Fusion cannot reach an outcome.'
                : 'Corroboration is insufficient.';
    return {
      value,
      model,
      kind: 'advisory',
      label: 'Advisory risk index',
      detail: `The engine decision is undetermined: ${explanation} The Spam, Ham or Pub verdict above follows the recorded classification and recipient policy. This risk index is advisory, not a spam probability.`,
    };
  }
  if (report ? report.score.kind === 'decision' : useDecision && decision?.source === 'fusion')
    return {
      value,
      model,
      kind: 'decision',
      label: 'Fusion estimate',
      detail:
        'Fusion model estimate for its validated population.',
    };
  return {
    value,
    model,
    kind: 'content',
    label: 'Risk index',
    detail:
      'Recorded content risk on a 0–100 scale. It is not a spam probability.',
  };
}

export type Arbitration = {
  version: string;
  baseline: { outcome: string; score: number | null };
  opinion: string;
  resolution: 'agreement' | 'disagreement' | 'ambiguous' | 'corroborated';
  decision: { outcome: string; score: number | null };
};

export function arbitrationExplanation(report?: Arbitration | null, resolution?: Assessment['score_resolution']) {
  if (!report) return null;
  const label = (outcome: string) =>
    ({ legitimate: 'Legitimate', unwanted: 'Spam', undetermined: 'Undetermined' })[
      outcome
    ] ?? 'Undetermined';
  return {
    title: {
      agreement: 'Opinions agree',
      disagreement: 'Opinions disagree',
      ambiguous: 'Uncertain second opinion',
      corroborated: 'Corroborating signals',
    }[report.resolution],
    detail: `Recorded baseline: ${label(report.baseline.outcome)}. Second opinion: ${label(report.opinion)}. ${resolution ? `Automatic threshold policy: ${label(resolution.decision.outcome)}. The original disagreement is retained as a diagnostic.` : report.decision.outcome === 'undetermined' ? 'The engine abstains; recipient rules can determine classification and delivery.' : 'These opinions are not independent evidence.'}`,
  };
}

export function checkFailure(reason?: string | null) {
  if (!reason) return '';
  return (
    (
      {
        input: 'Content cannot be processed by this check',
        storage: 'Cache or quota storage unavailable',
        budget_storage: 'Budget accounting unavailable',
        timeout: 'Deadline exceeded',
        network: 'Connection or TLS verification failed',
        authentication: 'Provider authentication rejected',
        rate_limit: 'Provider rate limit',
        provider_backoff: 'Provider cooldown after an error or refusal',
        http: 'Provider HTTP error',
        response_limit: 'Response exceeds the allowed limit',
        invalid_response: 'Invalid or incompatible response',
        accounting: 'Token usage exceeds the reserved budget',
      } as Record<string, string>
    )[reason] ?? 'Unknown cause'
  );
}

export function publicitySignal(
  report?: { status: string; verdict: string } | null,
) {
  return (
    report?.status === 'complete' &&
    ['promotion', 'newsletter'].includes(report.verdict)
  );
}

// Primary delivery labels are always Spam / Ham / Pub. Coverage and detailed
// threats remain separate. Historical fallbacks never rewrite stored receipts.
export function classification(mail: DecisionInput, _threshold?: number) {
  const record = receiptDecision(mail);
  const report = receiptAssessment(mail);
  const category = report?.category ?? mail.delivery_classification;
  const label = (value: string, fallback = false) => ({
    label: value === 'spam' ? 'Spam' : value === 'publicity' ? 'Pub' : 'Ham',
    tone: value === 'spam' ? 'spam' : value === 'publicity' ? 'publicity' : fallback ? 'neutral' : 'good',
  });
  if (record && ['phishing', 'malware'].includes(record.classification)) return label('spam');
  if (!record && mail.decision?.source === 'antivirus') return label('spam');
  if (category && category !== 'undetermined')
    return label(category, record?.classification === 'unassessed' || report?.score_resolution?.score === null);
  if (!report && !category && mail.decision?.outcome === 'unwanted') return label('spam');
  if (!report && !category && mail.decision?.outcome === 'legitimate')
    return label(mail.category === 'publicity' ? 'publicity' : 'legitimate');
  return label('legitimate', true);
}

export function classificationDetail(mail: DecisionInput): string {
  const record = receiptDecision(mail);
  const report = receiptAssessment(mail);
  if (record && ['phishing', 'malware'].includes(record.classification))
    return `Spam — ${record.classification} detected.`;
  if (classification(mail).label === 'Ham' && (record?.classification === 'unassessed' || report?.category === 'undetermined'
      || (!report && !mail.delivery_classification && mail.decision?.outcome !== 'unwanted' && mail.decision?.outcome !== 'legitimate')))
    return 'Ham — fail-open grouping: insufficient recorded evidence. This is not a safety guarantee. The original analysis and delivery remain unchanged.';
  if (classification(mail).label === 'Ham' && report?.score_resolution?.score === null)
    return 'Ham — accepted without a usable score. Analysis details remain available.';
  return 'NoiseFence verdict. Analysis coverage and delivery actions are shown separately.';
}

export function deliverySummary(recipients: { status: string }[]) {
  if (!recipients.length) return { label: 'Not recorded', tone: '' };
  const statuses = new Set(recipients.map((r) => r.status));
  if (statuses.has('quarantined'))
    return { label: 'Quarantined', tone: 'quarantine-status' };
  if (statuses.size === 1 && statuses.has('dsn_suppressed'))
    return { label: 'Notification suppressed (backscatter protection)', tone: 'spam' };
  if (statuses.has('failed') || statuses.has('notified') || statuses.has('dsn_suppressed'))
    return { label: 'Delivery failed', tone: 'spam' };
  if (statuses.has('pending') || statuses.has('sending'))
    return { label: 'In progress', tone: 'review' };
  if (statuses.size === 1 && statuses.has('delivered'))
    return { label: 'Accepted by destination', tone: 'good' };
  if (statuses.size === 1 && statuses.has('expired'))
    return { label: 'Expired', tone: '' };
  if (statuses.size === 1 && statuses.has('discarded'))
    return { label: 'Discarded', tone: '' };
  return { label: 'Mixed delivery states', tone: '' };
}

export function matchesAccount(
  account: {
    username: string;
    addresses: string[];
    admin: boolean;
    disabled: boolean;
  },
  query: string,
  filter: string,
) {
  const needle = query.trim().toLocaleLowerCase('en-GB');
  return (
    (filter === 'all' ||
      (filter === 'admin' && account.admin) ||
      (filter === 'user' && !account.admin) ||
      (filter === 'disabled' && account.disabled)) &&
    (!needle ||
      [account.username, ...account.addresses].some((v) =>
        v.toLocaleLowerCase('en-GB').includes(needle),
      ))
  );
}
