import { type Assessment, missingCheckLabels } from './assessment.ts';

type DecisionInput = {
  assessment?: Assessment;
  delivery_classification?: string | null;
  category: string;
  complete: boolean;
  score: number;
  tagged: boolean;
  pub_tagged: boolean;
  decision?: { source: string; outcome: string; score: number | null };
};

export type ScoreInput = {
  assessment?: Assessment;
  score: number | null;
  complete: boolean;
  model?: string;
  decision?: {
    source: string;
    outcome: string;
    score: number | null;
    model?: string;
  } | null;
  arbitration?: { resolution: string } | null;
  reasons?: { id: string }[];
  evidence?: { lexical_state?: string } | null;
  antivirus?: { status: string };
};

// A missing decision score is an abstention, not a missing content score.
// This presentation must never feed classification, thresholds or delivery.
export function scorePresentation(mail: ScoreInput) {
  const valid = (value: unknown): value is number =>
    typeof value === 'number' &&
    Number.isFinite(value) &&
    value >= 0 &&
    value <= 100;
  const useDecision =
    mail.decision?.source !== 'antivirus' && valid(mail.decision?.score);
  const report = mail.assessment?.version === 1 ? mail.assessment : undefined;
  const value = report
    ? (valid(report.score.value) ? report.score.value : null)
    : useDecision
    ? mail.decision!.score
    : valid(mail.score)
      ? mail.score
      : null;
  const model = report?.score.model ?? (useDecision ? mail.decision?.model : mail.model) ?? '';
  const complete = report?.complete ?? mail.complete;
  if (value === null)
    return {
      value,
      model,
      kind: 'unavailable',
      label: 'Score unavailable',
      detail:
        'No usable score was recorded. Missing analysis cannot be represented by zero.',
    };

  if (!complete) {
    const controls = missingCheckLabels;
    const missing = [
      ...new Set(
        (report?.incomplete_reasons ?? (mail.reasons ?? []).map(r => r.id))
          .map((id) => (Object.hasOwn(controls, id) ? controls[id] : null))
          .filter(Boolean),
      ),
    ];
    if (!report && ['unavailable', 'unscannable'].includes(mail.antivirus?.status ?? ''))
      missing.push('antivirus');
    const limited = mail.evidence?.lexical_state === 'limited';
    return {
      value,
      model,
      kind: 'partial',
      label: 'Partial risk index',
      detail: `Risk index based on available results${limited ? ', with limited content extraction' : ''}. ${missing.length ? `Incomplete checks: ${missing.join(', ')}. ` : ''}Missing results could change this index. Analysis remains partial.${mail.decision?.source === 'antivirus' ? ' The antivirus detection takes priority.' : ''}`,
    };
  }
  if (report ? report.score.kind === 'internal' : mail.model === 'dsn')
    return {
      value,
      model,
      kind: 'internal',
      label: 'Internal value',
      detail:
        'Delivery notification generated by NoiseFence. This stored value is not an analysis of incoming mail.',
    };
  if (mail.decision?.source === 'antivirus')
    return {
      value,
      model,
      kind: 'advisory',
      label: 'Advisory risk index',
      detail:
        'Recorded content index. Malware detected by the antivirus takes priority over this score.',
    };
  if (mail.decision?.outcome === 'undetermined') {
    const reason =
      mail.arbitration?.resolution === 'disagreement'
        ? 'Detector opinions disagree.'
        : mail.arbitration?.resolution === 'ambiguous'
          ? 'The second opinion is uncertain.'
          : mail.decision.source === 'fusion'
            ? 'Fusion cannot reach a decision.'
            : 'Corroboration is insufficient.';
    return {
      value,
      model,
      kind: 'advisory',
      label: 'Advisory risk index',
      detail: `${reason} The score remains visible while the engine decision is undetermined. Recipient rules may still apply. This index is not a spam probability.`,
    };
  }
  if (report ? report.score.kind === 'decision' : useDecision && mail.decision?.source === 'fusion')
    return {
      value,
      model,
      kind: 'decision',
      label: 'Fusion estimate',
      detail:
        'Fusion model estimate for its validated population.',
    };
  return {
    value,
    model,
    kind: 'content',
    label: 'Risk index',
    detail:
      'Recorded content risk on a 0–100 scale. It is not a spam probability.',
  };
}

export type Arbitration = {
  version: string;
  baseline: { outcome: string; score: number | null };
  opinion: string;
  resolution: 'agreement' | 'disagreement' | 'ambiguous' | 'corroborated';
  decision: { outcome: string; score: number | null };
};

export function arbitrationExplanation(report?: Arbitration | null) {
  if (!report) return null;
  const label = (outcome: string) =>
    ({ legitimate: 'Legitimate', unwanted: 'Spam', undetermined: 'Undetermined' })[
      outcome
    ] ?? 'Undetermined';
  return {
    title: {
      agreement: 'Opinions agree',
      disagreement: 'Opinions disagree',
      ambiguous: 'Uncertain second opinion',
      corroborated: 'Corroborating signals',
    }[report.resolution],
    detail: `Recorded baseline: ${label(report.baseline.outcome)}. Second opinion: ${label(report.opinion)}. ${report.decision.outcome === 'undetermined' ? 'The engine abstains; recipient rules can determine classification and delivery.' : 'These opinions are not independent evidence.'}`,
  };
}

export function checkFailure(reason?: string | null) {
  if (!reason) return '';
  return (
    (
      {
        input: 'Content cannot be processed by this check',
        storage: 'Cache or quota storage unavailable',
        budget_storage: 'Budget accounting unavailable',
        timeout: 'Deadline exceeded',
        network: 'Connection or TLS verification failed',
        authentication: 'Provider authentication rejected',
        rate_limit: 'Provider rate limit',
        http: 'Provider HTTP error',
        response_limit: 'Response exceeds the allowed limit',
        invalid_response: 'Invalid or incompatible response',
        accounting: 'Token usage exceeds the reserved budget',
      } as Record<string, string>
    )[reason] ?? 'Unknown cause'
  );
}

export function publicitySignal(
  report?: { status: string; verdict: string } | null,
) {
  return (
    report?.status === 'complete' &&
    ['promotion', 'newsletter'].includes(report.verdict)
  );
}

// Keep the canonical decision distinct from the delivery action and feedback.
export function classification(mail: DecisionInput, threshold?: number) {
  if (mail.decision?.source === 'antivirus')
    return { label: 'Malware', tone: 'spam' };

  const recordedCategory = mail.assessment?.version === 1 ? mail.assessment.category : mail.delivery_classification;
  if (recordedCategory)
    return (
      (
        {
          spam: { label: 'Spam', tone: 'spam' },
          publicity: { label: 'Marketing', tone: 'publicity' },
          legitimate: { label: 'Legitimate', tone: 'good' },
          undetermined: { label: 'Needs review', tone: 'review' },
        } as Record<string, { label: string; tone: string }>
      )[recordedCategory] || { label: 'Needs review', tone: 'review' }
    );
  if (!mail.complete && !mail.decision) return { label: 'Needs review', tone: 'review' };
  if (
    !mail.decision &&
    (threshold === undefined || !Number.isFinite(threshold))
  )
    return { label: 'Historical classification unavailable', tone: 'review' };
  if (
    mail.decision?.outcome === 'unwanted' ||
    (!mail.decision && threshold !== undefined && mail.score >= threshold)
  )
    return { label: 'Spam', tone: 'spam' };
  if (
    mail.decision?.outcome === 'undetermined' ||
    mail.category === 'undetermined'
  )
    return { label: 'Needs review', tone: 'review' };
  if (mail.category === 'publicity') return { label: 'Marketing', tone: 'publicity' };
  return { label: 'Legitimate', tone: 'good' };
}

export function deliverySummary(recipients: { status: string }[]) {
  if (!recipients.length) return { label: 'Not recorded', tone: '' };
  const statuses = new Set(recipients.map((r) => r.status));
  if (statuses.has('quarantined'))
    return { label: 'Quarantined', tone: 'quarantine-status' };
  if (statuses.size === 1 && statuses.has('dsn_suppressed'))
    return { label: 'Notification suppressed (backscatter protection)', tone: 'spam' };
  if (statuses.has('failed') || statuses.has('notified') || statuses.has('dsn_suppressed'))
    return { label: 'Delivery failed', tone: 'spam' };
  if (statuses.has('pending') || statuses.has('sending'))
    return { label: 'In progress', tone: 'review' };
  if (statuses.size === 1 && statuses.has('delivered'))
    return { label: 'Accepted by destination', tone: 'good' };
  if (statuses.size === 1 && statuses.has('expired'))
    return { label: 'Expired', tone: '' };
  if (statuses.size === 1 && statuses.has('discarded'))
    return { label: 'Discarded', tone: '' };
  return { label: 'Mixed delivery states', tone: '' };
}

export function matchesAccount(
  account: {
    username: string;
    addresses: string[];
    admin: boolean;
    disabled: boolean;
  },
  query: string,
  filter: string,
) {
  const needle = query.trim().toLocaleLowerCase('en-GB');
  return (
    (filter === 'all' ||
      (filter === 'admin' && account.admin) ||
      (filter === 'user' && !account.admin) ||
      (filter === 'disabled' && account.disabled)) &&
    (!needle ||
      [account.username, ...account.addresses].some((v) =>
        v.toLocaleLowerCase('en-GB').includes(needle),
      ))
  );
}
