-- Management authority only. There are deliberately no spool bodies, SMTP
-- delivery leases or HA body acknowledgements in PostgreSQL.
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA noisefence;
CREATE TEXT SEARCH CONFIGURATION noisefence.search (COPY=pg_catalog.simple);
ALTER TEXT SEARCH CONFIGURATION noisefence.search
 ALTER MAPPING FOR hword,hword_part,word WITH noisefence.unaccent,pg_catalog.simple;
CREATE TABLE noisefence.users (
 username text PRIMARY KEY, password text NOT NULL,
 admin boolean NOT NULL DEFAULT false, disabled boolean NOT NULL DEFAULT false,
 version bigint NOT NULL DEFAULT 0 CHECK(version>=0)
);
CREATE TABLE noisefence.grants (
 username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 address text NOT NULL, PRIMARY KEY(username,address)
);
CREATE TABLE noisefence.sessions (
 token_hash text PRIMARY KEY CHECK(length(token_hash)=64),
 username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 csrf text NOT NULL, expires bigint NOT NULL, mfa_verified boolean NOT NULL DEFAULT false
);
CREATE INDEX sessions_expiry ON noisefence.sessions(expires);
CREATE TABLE noisefence.mfa_credentials (
 username text PRIMARY KEY REFERENCES noisefence.users ON DELETE CASCADE,
 secret bytea NOT NULL, enabled boolean NOT NULL DEFAULT false,
 pending_until bigint NOT NULL, last_step bigint NOT NULL DEFAULT -1
);
CREATE TABLE noisefence.mfa_recovery (
 username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 digest text NOT NULL, PRIMARY KEY(username,digest)
);
CREATE TABLE noisefence.mfa_attempts (
 username text PRIMARY KEY REFERENCES noisefence.users ON DELETE CASCADE,
 until bigint NOT NULL, attempts integer NOT NULL
);
CREATE TABLE noisefence.invitations (
 id text PRIMARY KEY, token_hash text NOT NULL UNIQUE,
 username text NOT NULL, admin boolean NOT NULL, addresses jsonb NOT NULL CHECK(jsonb_typeof(addresses)='array'),
 creator text NOT NULL REFERENCES noisefence.users,
 creator_version bigint NOT NULL, created bigint NOT NULL, expires bigint NOT NULL,
 version bigint NOT NULL DEFAULT 1, revoked bigint, accepted bigint
);
CREATE INDEX invitation_expiry ON noisefence.invitations(expires);
CREATE TABLE noisefence.audit (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created bigint NOT NULL, username text NOT NULL, action text NOT NULL, object_id text NOT NULL
);
CREATE INDEX audit_created ON noisefence.audit(created DESC,id DESC);
CREATE INDEX audit_catalog_object ON noisefence.audit(object_id,created) WHERE action IN ('model_set_retain_started','model_set_retain_completed','model_set_retain_failed','model_set_remove_started','model_set_remove_completed','model_set_remove_failed');
CREATE TABLE noisefence.policy_revisions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 created bigint NOT NULL, username text NOT NULL,
 settings jsonb NOT NULL CHECK(jsonb_typeof(settings)='object'),
 sha256 text NOT NULL CHECK(length(sha256)=64)
);
-- A committed policy proposal and the locally activated policy are distinct.
CREATE TABLE noisefence.policy_head (
 id integer PRIMARY KEY CHECK(id=1), revision bigint NOT NULL REFERENCES noisefence.policy_revisions,
 activated_at bigint, activation_epoch jsonb
);
CREATE TABLE noisefence.sources (
 node text PRIMARY KEY, epoch text NOT NULL, enabled boolean NOT NULL DEFAULT true,
 created bigint NOT NULL, last_seen bigint, last_sequence bigint NOT NULL DEFAULT 0,
 UNIQUE(node,epoch)
);
CREATE TABLE noisefence.cluster_nodes (
 node text PRIMARY KEY, epoch text NOT NULL, name text NOT NULL,
 token_hash text NOT NULL CHECK(length(token_hash)=64),
 enabled boolean NOT NULL DEFAULT true, created bigint NOT NULL,
 version bigint NOT NULL DEFAULT 0, last_seen bigint,
 applied_revision bigint, applied_digest text, status jsonb NOT NULL DEFAULT '{}',
 FOREIGN KEY(node,epoch) REFERENCES noisefence.sources(node,epoch)
);
-- Central policy authority; local participants retain their own admission fence.
CREATE TABLE noisefence.policy_authority (
 id integer PRIMARY KEY CHECK(id=1), node text NOT NULL, epoch text NOT NULL,
 journal jsonb NOT NULL CHECK(jsonb_typeof(journal)='object'),
 membership jsonb NOT NULL CHECK(jsonb_typeof(membership)='object'),
 actor text, actor_version bigint, session_hash text, scope text, incident jsonb,
 FOREIGN KEY(node,epoch) REFERENCES noisefence.sources(node,epoch)
);
CREATE TABLE noisefence.policy_peers (
 node text PRIMARY KEY, epoch text NOT NULL, seen bigint NOT NULL,
 protocol text NOT NULL, build text NOT NULL, revision bigint NOT NULL,
 digest text NOT NULL CHECK(length(digest) IN (0,64)),
 FOREIGN KEY(node,epoch) REFERENCES noisefence.sources(node,epoch)
);
-- Retain only identity/generation after deletion, so delayed retries cannot
-- resurrect private metadata. No subject, sender or analysis enters tombstones.
CREATE TABLE noisefence.message_versions (
 id text PRIMARY KEY, node text NOT NULL, epoch text NOT NULL,
 generation bigint NOT NULL CHECK(generation>0), deleted boolean NOT NULL,
 FOREIGN KEY(node,epoch) REFERENCES noisefence.sources(node,epoch)
);
CREATE TABLE noisefence.messages (
 id text PRIMARY KEY REFERENCES noisefence.message_versions ON DELETE CASCADE,
 created bigint NOT NULL, sender text NOT NULL,
 scan jsonb NOT NULL CHECK(jsonb_typeof(scan)='object'),
 is_dsn boolean NOT NULL, raw_present boolean NOT NULL,
 updated_at bigint NOT NULL DEFAULT (EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint),
 category text NOT NULL CHECK(category IN ('spam','publicity','legitimate','undetermined')),
 score double precision CHECK(score BETWEEN 0 AND 100),
 rules text NOT NULL,
 subject text GENERATED ALWAYS AS (left(coalesce(scan->>'subject',''),4096)) STORED,
 subject_search tsvector GENERATED ALWAYS AS (to_tsvector('noisefence.search',left(coalesce(scan->>'subject',''),4096))) STORED,
 rule_search tsvector GENERATED ALWAYS AS (to_tsvector('noisefence.search',rules)) STORED,
 search_document tsvector GENERATED ALWAYS AS (
  to_tsvector('noisefence.search', left(coalesce(scan->>'subject',''),4096) || ' ' || left(sender,1024) || ' ' || rules)
 ) STORED
);
CREATE INDEX messages_created ON noisefence.messages(created DESC,id DESC);
CREATE INDEX messages_search ON noisefence.messages USING gin(search_document);
CREATE INDEX messages_subject_search ON noisefence.messages USING gin(subject_search);
CREATE INDEX messages_rule_search ON noisefence.messages USING gin(rule_search);
CREATE INDEX messages_category_created ON noisefence.messages(category,created DESC,id DESC);
CREATE TABLE noisefence.deliveries (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 message_id text NOT NULL REFERENCES noisefence.messages ON DELETE CASCADE,
 address text NOT NULL, destination text NOT NULL,
 status text NOT NULL, attempts bigint NOT NULL, next_attempt bigint NOT NULL,
 error text, action text CHECK(action IN ('deliver','tag','quarantine')),
 held_until bigint, released_at bigint, filtering jsonb,
 logs jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(logs)='array'),
 UNIQUE(message_id,address)
);
CREATE INDEX deliveries_destination ON noisefence.deliveries(destination,message_id);
CREATE INDEX deliveries_message ON noisefence.deliveries(message_id);
-- UUID/source/sequence tombstones contain no SMTP transcript or recipient text.
CREATE TABLE noisefence.delivery_log_versions (
 node text NOT NULL, epoch text NOT NULL, local_id bigint NOT NULL CHECK(local_id>0),
 message_id text NOT NULL REFERENCES noisefence.message_versions,
 delivery_id bigint REFERENCES noisefence.deliveries ON DELETE SET NULL,
 generation bigint NOT NULL CHECK(generation>0), deleted boolean NOT NULL,
 PRIMARY KEY(node,epoch,local_id),
 FOREIGN KEY(node,epoch) REFERENCES noisefence.sources(node,epoch)
);
CREATE INDEX log_version_delivery ON noisefence.delivery_log_versions(delivery_id,local_id DESC);
CREATE TABLE noisefence.delivery_logs (
 node text NOT NULL, epoch text NOT NULL, local_id bigint NOT NULL,
 message_id text NOT NULL REFERENCES noisefence.messages ON DELETE CASCADE,
 attempt bigint NOT NULL CHECK(attempt>=0), trace jsonb NOT NULL CHECK(jsonb_typeof(trace)='object'),
 PRIMARY KEY(node,epoch,local_id),
 FOREIGN KEY(node,epoch,local_id) REFERENCES noisefence.delivery_log_versions ON DELETE CASCADE
);
CREATE VIEW noisefence.console_access AS
 SELECT u.username,d.id AS delivery_id FROM noisefence.users u CROSS JOIN noisefence.deliveries d
 WHERE NOT u.disabled AND (u.admin OR EXISTS(
  SELECT 1 FROM noisefence.grants g WHERE g.username=u.username AND (
   g.address=d.destination OR
   (left(g.address,2)='*@' AND (lower(split_part(d.destination,'@',2))=lower(substr(g.address,3))
                         OR lower(split_part(d.address,'@',2))=lower(substr(g.address,3))))
  )
 ));
CREATE TABLE noisefence.feedback (
 username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 message_id text NOT NULL REFERENCES noisefence.messages ON DELETE CASCADE,
 spam boolean NOT NULL, category text CHECK(category IN ('spam','publicity','legitimate')),
 created bigint NOT NULL, PRIMARY KEY(username,message_id),
 CHECK(category IS NULL OR spam=(category='spam'))
);
CREATE TABLE noisefence.quality_batches (
 id text PRIMARY KEY, username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 created bigint NOT NULL, since bigint NOT NULL, until bigint NOT NULL,
 domain text NOT NULL, seed text NOT NULL, population bigint NOT NULL, selected bigint NOT NULL,
 purpose text NOT NULL CHECK(purpose IN ('development','regression','holdout')),
 cohort text NOT NULL DEFAULT '', provenance jsonb
);
CREATE TABLE noisefence.quality_members (
 batch_id text NOT NULL REFERENCES noisefence.quality_batches ON DELETE CASCADE,
 message_id text NOT NULL REFERENCES noisefence.messages ON DELETE CASCADE,
 rank bigint NOT NULL, PRIMARY KEY(batch_id,message_id)
);
CREATE INDEX quality_member_order ON noisefence.quality_members(batch_id,rank);
CREATE TABLE noisefence.quality_reference_sets (
 batch_id text PRIMARY KEY REFERENCES noisefence.quality_batches ON DELETE CASCADE,
 provenance text NOT NULL
);
CREATE TABLE noisefence.quality_labels (
 username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 message_id text NOT NULL REFERENCES noisefence.messages ON DELETE CASCADE,
 risk text NOT NULL CHECK(risk IN ('legitimate','spam','uncertain')),
 kind text CHECK(kind IN ('conversation','transactional','notification','newsletter','promotion','other')),
 created bigint NOT NULL, PRIMARY KEY(username,message_id)
);
CREATE TABLE noisefence.quality_reserved (
 message_id text PRIMARY KEY REFERENCES noisefence.messages ON DELETE CASCADE,
 created bigint NOT NULL, reason text NOT NULL
);
CREATE VIEW noisefence.quality_protected_messages AS
 SELECT message_id FROM noisefence.quality_reserved UNION
 SELECT x.message_id FROM noisefence.quality_members x JOIN noisefence.quality_batches p ON p.id=x.batch_id
 WHERE p.purpose!='development';
CREATE VIEW noisefence.training_feedback AS
 SELECT f.* FROM noisefence.feedback f WHERE NOT EXISTS(SELECT 1 FROM noisefence.quality_labels q WHERE q.message_id=f.message_id)
 AND NOT EXISTS(SELECT 1 FROM noisefence.quality_protected_messages p WHERE p.message_id=f.message_id);
CREATE TABLE noisefence.adaptive_labels (
 username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 message_id text NOT NULL REFERENCES noisefence.messages ON DELETE CASCADE,
 domain text NOT NULL, class text NOT NULL CHECK(class IN ('legitimate','publicity','spam','phishing','scam')),
 created bigint NOT NULL, PRIMARY KEY(username,message_id,domain)
);
CREATE INDEX adaptive_labels_domain ON noisefence.adaptive_labels(domain,created);
CREATE FUNCTION noisefence.invalidate_adaptive_label() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN
  DELETE FROM noisefence.adaptive_labels WHERE username=OLD.username AND message_id=OLD.message_id;
  RETURN OLD;
 END IF;
 DELETE FROM noisefence.adaptive_labels WHERE username=NEW.username AND message_id=NEW.message_id;
 RETURN NEW;
END $$;
CREATE TRIGGER adaptive_label_invalidate AFTER UPDATE OF spam,created OR DELETE ON noisefence.feedback
 FOR EACH ROW EXECUTE FUNCTION noisefence.invalidate_adaptive_label();
CREATE TABLE noisefence.quality_jobs (
 id text PRIMARY KEY, username text NOT NULL REFERENCES noisefence.users ON DELETE CASCADE,
 batch_id text NOT NULL REFERENCES noisefence.quality_batches ON DELETE CASCADE,
 operation text NOT NULL CHECK(operation IN ('train','compare','evaluate')),
 candidate_id text, status text NOT NULL CHECK(status IN ('queued','running','complete','insufficient_labels','failed','cancelled','interrupted')),
 created bigint NOT NULL, started bigint, finished bigint, report jsonb, model_sha256 text
);
CREATE INDEX quality_job_queue ON noisefence.quality_jobs(status,created);
CREATE TABLE noisefence.quality_worker_status (
 id integer PRIMARY KEY CHECK(id=1), heartbeat bigint NOT NULL, build text NOT NULL
);
CREATE TABLE noisefence.quality_exposure_state (
 id integer PRIMARY KEY CHECK(id=1), tracking_since bigint NOT NULL, generation bigint NOT NULL DEFAULT 0
);
INSERT INTO noisefence.quality_exposure_state(id,tracking_since) VALUES(1,EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::bigint);
CREATE TABLE noisefence.quality_export_batches (batch_id text PRIMARY KEY,exposed_at bigint NOT NULL);
CREATE TABLE noisefence.quality_export_campaigns (
 fingerprint text NOT NULL,simhash text NOT NULL,exposed_at bigint NOT NULL,PRIMARY KEY(fingerprint,simhash)
);
CREATE TABLE noisefence.queue_commands (
 id text PRIMARY KEY, node text NOT NULL REFERENCES noisefence.sources,
 node_epoch text NOT NULL,
 message_id text NOT NULL, recipient text NOT NULL, command text NOT NULL CHECK(command IN ('release','delete','retry')),
 username text NOT NULL, session_hash text NOT NULL CHECK(length(session_hash)=64), actor_version bigint NOT NULL,
 created bigint NOT NULL, expires bigint NOT NULL,
 result text, finished bigint, execution_result text, executed_at bigint
);
CREATE UNIQUE INDEX pending_queue_command ON noisefence.queue_commands(node,message_id,recipient) WHERE finished IS NULL;
CREATE TABLE noisefence.command_tombstones (
 id text PRIMARY KEY, node text NOT NULL, epoch text NOT NULL,
 execution_result text, executed_at bigint,
 FOREIGN KEY(node,epoch) REFERENCES noisefence.sources(node,epoch)
);
CREATE TABLE noisefence.migration_state (
 id integer PRIMARY KEY CHECK(id=1), source_digest text NOT NULL,
 imported_at bigint NOT NULL, activated_at bigint, report jsonb NOT NULL
);

-- Monotonic detector-cache publications; never used for SMTP acceptance.
CREATE SEQUENCE noisefence.runtime_history_generation;
